/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sports.club.management.system;

/**
 *
 * @author Harshil
 */
import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holder = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        infrastructure = new javax.swing.JButton();
        players = new javax.swing.JButton();
        analysis = new javax.swing.JButton();
        sports = new javax.swing.JButton();
        staff = new javax.swing.JButton();
        sponsors = new javax.swing.JButton();
        guests = new javax.swing.JButton();
        imagemini = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPORTS CLUB MANAGEMENT SYSTEM\n");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        holder.setLayout(null);

        header.setBackground(new java.awt.Color(255, 204, 51));
        header.setFont(new java.awt.Font("Times New Roman", 1, 66)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Sports  Club  Management  System");
        header.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header.setOpaque(true);
        holder.add(header);
        header.setBounds(10, 10, 1520, 85);

        logout.setBackground(new java.awt.Color(255, 204, 51));
        logout.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        holder.add(logout);
        logout.setBounds(1360, 120, 110, 30);

        infrastructure.setBackground(new java.awt.Color(255, 255, 153));
        infrastructure.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        infrastructure.setText("INFRASTRUCTURE");
        infrastructure.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infrastructure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infrastructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infrastructureActionPerformed(evt);
            }
        });
        holder.add(infrastructure);
        infrastructure.setBounds(200, 260, 300, 120);

        players.setBackground(new java.awt.Color(255, 255, 153));
        players.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        players.setText("PLAYERS");
        players.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        players.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playersActionPerformed(evt);
            }
        });
        holder.add(players);
        players.setBounds(1070, 270, 200, 110);

        analysis.setBackground(new java.awt.Color(255, 255, 51));
        analysis.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        analysis.setText("ANALYSIS");
        analysis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        analysis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisActionPerformed(evt);
            }
        });
        holder.add(analysis);
        analysis.setBounds(620, 410, 320, 100);

        sports.setBackground(new java.awt.Color(255, 255, 102));
        sports.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        sports.setText("SPORTS");
        sports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsActionPerformed(evt);
            }
        });
        holder.add(sports);
        sports.setBounds(690, 170, 200, 110);

        staff.setBackground(new java.awt.Color(255, 255, 102));
        staff.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        staff.setText("STAFF");
        staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });
        holder.add(staff);
        staff.setBounds(250, 540, 230, 110);

        sponsors.setBackground(new java.awt.Color(255, 255, 153));
        sponsors.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        sponsors.setText("SPONSORS\n");
        sponsors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sponsors.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sponsors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sponsorsActionPerformed(evt);
            }
        });
        holder.add(sponsors);
        sponsors.setBounds(680, 630, 210, 110);

        guests.setBackground(new java.awt.Color(255, 255, 102));
        guests.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        guests.setText("GUESTS");
        guests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guests.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestsActionPerformed(evt);
            }
        });
        holder.add(guests);
        guests.setBounds(1070, 530, 200, 110);

        imagemini.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harshil\\Pictures\\Saved Pictures\\mini.jpg")); // NOI18N
        holder.add(imagemini);
        imagemini.setBounds(0, 0, 1538, 806);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(holder, javax.swing.GroupLayout.DEFAULT_SIZE, 1538, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(holder, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1552, 843));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JOptionPane.showMessageDialog(imagemini, "SUCCESSFULLY LOGGED OUT", "LOGOUT",JOptionPane.INFORMATION_MESSAGE);
        new SCMS().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void sportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsActionPerformed
        new Sports().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_sportsActionPerformed

    private void playersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playersActionPerformed
        new Players().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_playersActionPerformed

    private void sponsorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sponsorsActionPerformed
        new Sponsors().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_sponsorsActionPerformed

    private void guestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestsActionPerformed
        new Guests().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_guestsActionPerformed

    private void infrastructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infrastructureActionPerformed
        new Infrastructure().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_infrastructureActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
       new Staff().setVisible(true);
       super.dispose();
    }//GEN-LAST:event_staffActionPerformed

    private void analysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisActionPerformed
       new Analysis().setVisible(true);
       super.dispose();
    }//GEN-LAST:event_analysisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analysis;
    private javax.swing.JButton guests;
    private javax.swing.JLabel header;
    private javax.swing.JPanel holder;
    private javax.swing.JLabel imagemini;
    private javax.swing.JButton infrastructure;
    private javax.swing.JButton logout;
    private javax.swing.JButton players;
    private javax.swing.JButton sponsors;
    private javax.swing.JButton sports;
    private javax.swing.JButton staff;
    // End of variables declaration//GEN-END:variables
}
