/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sports.club.management.system;

/**
 *
 * @author Harshil
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.table.*;
import java.sql.*;
import net.proteanit.sql.*;

public class Sponsors extends javax.swing.JFrame {

    /**
     * Creates new form Sports
     */
    public Sponsors() {
        initComponents();
        sponsortable.getTableHeader().setForeground(Color.darkGray);
        sponsortable.getTableHeader().setFont(new Font("Arial",Font.BOLD,14));
        sponsortable.setBackground(new Color(0,0,0,0));
        sponsorholder.setBackground(new Color(0,0,0,0));
        sponsorholder.getViewport().setOpaque(false);
        addsponsorholder.setVisible(false);
        removesponsorholder.setVisible(false);
        display();
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carrier = new javax.swing.JScrollPane();
        support = new javax.swing.JPanel();
        holder = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        addsponsor = new javax.swing.JButton();
        addsponsorholder = new javax.swing.JPanel();
        sportid = new javax.swing.JLabel();
        sponsoridtxt = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        addsponsorsubmit = new javax.swing.JButton();
        removesponsor = new javax.swing.JButton();
        removesponsorholder = new javax.swing.JPanel();
        sportid1 = new javax.swing.JLabel();
        sponsorid1txt = new javax.swing.JTextField();
        info = new javax.swing.JLabel();
        removesponsorsubmit = new javax.swing.JButton();
        sponsorholder = new javax.swing.JScrollPane();
        sponsortable = new javax.swing.JTable();
        sponsorheader = new javax.swing.JLabel();
        imagepic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPORTS CLUB MANAGEMENT SYSTEM ");
        setAlwaysOnTop(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        carrier.setBackground(new java.awt.Color(255, 255, 255));
        carrier.setBorder(null);
        carrier.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        carrier.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        carrier.setColumnHeaderView(null);
        carrier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carrier.setOpaque(false);

        support.setPreferredSize(new java.awt.Dimension(1538, 1300));

        holder.setLayout(null);

        header.setBackground(new java.awt.Color(255, 204, 51));
        header.setFont(new java.awt.Font("Times New Roman", 1, 66)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Sports  Club  Management  System");
        header.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header.setOpaque(true);
        holder.add(header);
        header.setBounds(10, 10, 1500, 85);

        home.setBackground(new java.awt.Color(255, 204, 51));
        home.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        home.setText("HOME");
        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        holder.add(home);
        home.setBounds(1270, 110, 110, 30);

        logout.setBackground(new java.awt.Color(255, 204, 51));
        logout.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        holder.add(logout);
        logout.setBounds(1390, 110, 110, 30);

        addsponsor.setBackground(new java.awt.Color(255, 255, 153));
        addsponsor.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        addsponsor.setText("ADD SPONSOR");
        addsponsor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addsponsor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsponsor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addsponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsponsorActionPerformed(evt);
            }
        });
        holder.add(addsponsor);
        addsponsor.setBounds(320, 450, 160, 60);

        addsponsorholder.setOpaque(false);

        sportid.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        sportid.setText("SPONSOR ID");
        sportid.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        sponsoridtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sponsoridtxtKeyPressed(evt);
            }
        });

        name.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        name.setText("NAME");
        name.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nametxtKeyPressed(evt);
            }
        });

        addsponsorsubmit.setBackground(new java.awt.Color(255, 255, 102));
        addsponsorsubmit.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addsponsorsubmit.setText("SUBMIT");
        addsponsorsubmit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addsponsorsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsponsorsubmit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addsponsorsubmit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addsponsorsubmit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addsponsorsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsponsorsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addsponsorholderLayout = new javax.swing.GroupLayout(addsponsorholder);
        addsponsorholder.setLayout(addsponsorholderLayout);
        addsponsorholderLayout.setHorizontalGroup(
            addsponsorholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addsponsorholderLayout.createSequentialGroup()
                .addGroup(addsponsorholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sponsoridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addsponsorholderLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(addsponsorsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        addsponsorholderLayout.setVerticalGroup(
            addsponsorholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addsponsorholderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sportid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sponsoridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addsponsorsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        holder.add(addsponsorholder);
        addsponsorholder.setBounds(270, 510, 270, 180);

        removesponsor.setBackground(new java.awt.Color(255, 255, 153));
        removesponsor.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        removesponsor.setText("REMOVE SPONSOR");
        removesponsor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removesponsor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removesponsor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removesponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removesponsorActionPerformed(evt);
            }
        });
        holder.add(removesponsor);
        removesponsor.setBounds(620, 450, 210, 60);

        removesponsorholder.setOpaque(false);

        sportid1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        sportid1.setText("SPONSOR ID");
        sportid1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        sponsorid1txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sponsorid1txtKeyPressed(evt);
            }
        });

        info.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        info.setText("(Enter Sponsor Id of the Sponsor to be removed)");

        removesponsorsubmit.setBackground(new java.awt.Color(255, 255, 102));
        removesponsorsubmit.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        removesponsorsubmit.setText("SUBMIT");
        removesponsorsubmit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removesponsorsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removesponsorsubmit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removesponsorsubmit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        removesponsorsubmit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removesponsorsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removesponsorsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removesponsorholderLayout = new javax.swing.GroupLayout(removesponsorholder);
        removesponsorholder.setLayout(removesponsorholderLayout);
        removesponsorholderLayout.setHorizontalGroup(
            removesponsorholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removesponsorholderLayout.createSequentialGroup()
                .addGroup(removesponsorholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removesponsorholderLayout.createSequentialGroup()
                        .addGroup(removesponsorholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sportid1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sponsorid1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(removesponsorholderLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(removesponsorsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        removesponsorholderLayout.setVerticalGroup(
            removesponsorholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removesponsorholderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sportid1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sponsorid1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removesponsorsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        holder.add(removesponsorholder);
        removesponsorholder.setBounds(590, 510, 270, 130);

        sponsorholder.setBackground(new java.awt.Color(255, 255, 255));
        sponsorholder.setBorder(null);
        sponsorholder.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sponsorholder.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        sponsorholder.setOpaque(false);

        sponsortable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sponsortable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sponsortable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SPORTS ID", "NAME", "FEE", "TIMINGS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sponsortable.setEnabled(false);
        sponsortable.setGridColor(new java.awt.Color(0, 0, 0));
        sponsortable.setOpaque(false);
        sponsortable.setRowHeight(25);
        sponsortable.setRowMargin(2);
        sponsortable.setRowSelectionAllowed(false);
        sponsortable.setShowGrid(true);
        sponsortable.getTableHeader().setResizingAllowed(false);
        sponsortable.getTableHeader().setReorderingAllowed(false);
        sponsorholder.setViewportView(sponsortable);

        holder.add(sponsorholder);
        sponsorholder.setBounds(30, 210, 1460, 200);

        sponsorheader.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        sponsorheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sponsorheader.setText("SPONSORS");
        sponsorheader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        holder.add(sponsorheader);
        sponsorheader.setBounds(0, 130, 1538, 80);

        imagepic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagepic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harshil\\Pictures\\Saved Pictures\\pic.png")); // NOI18N
        imagepic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        holder.add(imagepic);
        imagepic.setBounds(-20, -20, 1580, 1340);

        javax.swing.GroupLayout supportLayout = new javax.swing.GroupLayout(support);
        support.setLayout(supportLayout);
        supportLayout.setHorizontalGroup(
            supportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, 1538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        supportLayout.setVerticalGroup(
            supportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        carrier.setViewportView(support);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(carrier, javax.swing.GroupLayout.DEFAULT_SIZE, 1538, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(carrier, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1552, 843));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insert()
    {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@Dell-HsB:1521:xe", "HSB", "4803");
            Statement stmt=con.createStatement();
            String query="insert into HSB.sponsors values ('"+sponsoridtxt.getText()+"','"+nametxt.getText()+"')";
            ResultSet rs=stmt.executeQuery(query);
            con.close();
            sponsoridtxt.setText(null);
            nametxt.setText(null);
            sponsoridtxt.requestFocus();
           } catch (Exception e) {
            JOptionPane.showMessageDialog(removesponsor, "SPORT ID ALREADY EXISTS", "ERROR", JOptionPane.ERROR_MESSAGE);
       } 
    }
    
    private void display()
    {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@Dell-HsB:1521:xe", "HSB", "4803");
            Statement stmt=con.createStatement();
            String query="select * from HSB.sponsors order by sponsor_id";
            ResultSet rs=stmt.executeQuery(query);
            sponsortable.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
           } catch (Exception e) {
            System.out.println(e);
       } 
    }
    
    private void remove()
    {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@Dell-HsB:1521:xe", "system", "0000");
            Statement stmt=con.createStatement();
            String query="delete HSB.sponsors where sponsor_id = '"+sponsorid1txt.getText()+"' ";
            ResultSet rs=stmt.executeQuery(query);
            con.close();
           } catch (Exception e) {
            System.out.println(e);
       } 
    }
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new Home().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JOptionPane.showMessageDialog(sponsortable, "SUCCESSFULLY LOGGED OUT", "LOGOUT",JOptionPane.INFORMATION_MESSAGE);
        new SCMS().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void removesponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removesponsorActionPerformed
        addsponsorholder.setVisible(false);
        removesponsorholder.setVisible(true);
    }//GEN-LAST:event_removesponsorActionPerformed

    private void addsponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsponsorActionPerformed
        removesponsorholder.setVisible(false);
        addsponsorholder.setVisible(true);
    }//GEN-LAST:event_addsponsorActionPerformed

    private void addsponsorsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsponsorsubmitActionPerformed
        if(sponsoridtxt.getText().isBlank()||nametxt.getText().isBlank())
        {
             JOptionPane.showMessageDialog(removesponsor, "ALL FIELDS ARE MANADATORY", "ERROR", JOptionPane.ERROR_MESSAGE);
        } 
        else
        {
        insert();
        display();
        }
    }//GEN-LAST:event_addsponsorsubmitActionPerformed

    private void removesponsorsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removesponsorsubmitActionPerformed
        if(sponsorid1txt.getText().isBlank())
        {
            JOptionPane.showMessageDialog(removesponsor, "ENTER VALID SPONSOR ID", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            remove();
            display();
            sponsorid1txt.setText(null);
        }
    }//GEN-LAST:event_removesponsorsubmitActionPerformed

    private void sponsoridtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sponsoridtxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
            nametxt.requestFocus();
        }
    }//GEN-LAST:event_sponsoridtxtKeyPressed

    private void nametxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           if(sponsoridtxt.getText().isBlank()||nametxt.getText().isBlank())
        {
             JOptionPane.showMessageDialog(removesponsor, "ALL FIELDS ARE MANADATORY", "ERROR", JOptionPane.ERROR_MESSAGE);
        } 
        else
        {
        insert();
        display();
        }
        }
        else
        {
            if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            sponsoridtxt.requestFocus();
        }
        }
    }//GEN-LAST:event_nametxtKeyPressed

    private void sponsorid1txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sponsorid1txtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           if(sponsorid1txt.getText().isBlank())
        {
            JOptionPane.showMessageDialog(removesponsor, "ENTER VALID SPONSOR ID", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            remove();
            display();
            sponsorid1txt.setText(null);
        }
        }   
    }//GEN-LAST:event_sponsorid1txtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new Sponsors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsponsor;
    private javax.swing.JPanel addsponsorholder;
    private javax.swing.JButton addsponsorsubmit;
    private javax.swing.JScrollPane carrier;
    private javax.swing.JLabel header;
    private javax.swing.JPanel holder;
    private javax.swing.JButton home;
    private javax.swing.JLabel imagepic;
    private javax.swing.JLabel info;
    private javax.swing.JButton logout;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton removesponsor;
    private javax.swing.JPanel removesponsorholder;
    private javax.swing.JButton removesponsorsubmit;
    private javax.swing.JLabel sponsorheader;
    private javax.swing.JScrollPane sponsorholder;
    private javax.swing.JTextField sponsorid1txt;
    private javax.swing.JTextField sponsoridtxt;
    private javax.swing.JTable sponsortable;
    private javax.swing.JLabel sportid;
    private javax.swing.JLabel sportid1;
    private javax.swing.JPanel support;
    // End of variables declaration//GEN-END:variables
}
