/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sports.club.management.system;

/**
 *
 * @author Harshil
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.table.*;
import java.sql.*;
import net.proteanit.sql.*;

public class Sports extends javax.swing.JFrame {

    /**
     * Creates new form Sports
     */
    public Sports() {
        initComponents();
        sportstable.getTableHeader().setForeground(Color.darkGray);
        sportstable.getTableHeader().setFont(new Font("Arial",Font.BOLD,14));
        sportstable.setBackground(new Color(0,0,0,0));
        sportsholder.setBackground(new Color(0,0,0,0));
        sportsholder.getViewport().setOpaque(false);
        addsportholder.setVisible(false);
        removesportholder.setVisible(false);
        display();
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carrier = new javax.swing.JScrollPane();
        support = new javax.swing.JPanel();
        holder = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        addsport = new javax.swing.JButton();
        addsportholder = new javax.swing.JPanel();
        sportid = new javax.swing.JLabel();
        sportidtxt = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        fee = new javax.swing.JLabel();
        feetxt = new javax.swing.JTextField();
        timings = new javax.swing.JLabel();
        timingstxt = new javax.swing.JTextField();
        addsportsubmit = new javax.swing.JButton();
        removesport = new javax.swing.JButton();
        removesportholder = new javax.swing.JPanel();
        sportid1 = new javax.swing.JLabel();
        sportid1txt = new javax.swing.JTextField();
        info = new javax.swing.JLabel();
        removesportsubmit1 = new javax.swing.JButton();
        sportsholder = new javax.swing.JScrollPane();
        sportstable = new javax.swing.JTable();
        sportsheader = new javax.swing.JLabel();
        imagepic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPORTS CLUB MANAGEMENT SYSTEM ");
        setAlwaysOnTop(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        carrier.setBackground(new java.awt.Color(255, 255, 255));
        carrier.setBorder(null);
        carrier.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        carrier.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        carrier.setColumnHeaderView(null);
        carrier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carrier.setOpaque(false);

        support.setPreferredSize(new java.awt.Dimension(1538, 1300));

        holder.setLayout(null);

        header.setBackground(new java.awt.Color(255, 204, 51));
        header.setFont(new java.awt.Font("Times New Roman", 1, 66)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Sports  Club  Management  System");
        header.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header.setOpaque(true);
        holder.add(header);
        header.setBounds(10, 10, 1500, 85);

        home.setBackground(new java.awt.Color(255, 204, 51));
        home.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        home.setText("HOME");
        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        holder.add(home);
        home.setBounds(1270, 110, 110, 30);

        logout.setBackground(new java.awt.Color(255, 204, 51));
        logout.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        holder.add(logout);
        logout.setBounds(1390, 110, 110, 30);

        addsport.setBackground(new java.awt.Color(255, 255, 153));
        addsport.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        addsport.setText("ADD SPORT");
        addsport.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addsport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addsport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsportActionPerformed(evt);
            }
        });
        holder.add(addsport);
        addsport.setBounds(320, 470, 160, 60);

        addsportholder.setOpaque(false);

        sportid.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        sportid.setText("SPORT ID");
        sportid.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        sportidtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sportidtxtKeyPressed(evt);
            }
        });

        name.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        name.setText("NAME");
        name.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nametxtKeyPressed(evt);
            }
        });

        fee.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        fee.setText("FEE");
        fee.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        feetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                feetxtKeyPressed(evt);
            }
        });

        timings.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        timings.setText("TIMINGS");
        timings.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        timingstxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                timingstxtKeyPressed(evt);
            }
        });

        addsportsubmit.setBackground(new java.awt.Color(255, 255, 102));
        addsportsubmit.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addsportsubmit.setText("SUBMIT");
        addsportsubmit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addsportsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsportsubmit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addsportsubmit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addsportsubmit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addsportsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsportsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addsportholderLayout = new javax.swing.GroupLayout(addsportholder);
        addsportholder.setLayout(addsportholderLayout);
        addsportholderLayout.setHorizontalGroup(
            addsportholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addsportholderLayout.createSequentialGroup()
                .addGroup(addsportholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timings, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timingstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addsportholderLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(addsportsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        addsportholderLayout.setVerticalGroup(
            addsportholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addsportholderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sportid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sportidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(feetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(timings, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(timingstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(addsportsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        holder.add(addsportholder);
        addsportholder.setBounds(270, 540, 270, 300);

        removesport.setBackground(new java.awt.Color(255, 255, 153));
        removesport.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        removesport.setText("REMOVE SPORT");
        removesport.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removesport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removesport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removesport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removesportActionPerformed(evt);
            }
        });
        holder.add(removesport);
        removesport.setBounds(640, 470, 180, 60);

        removesportholder.setOpaque(false);

        sportid1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        sportid1.setText("SPORT ID");
        sportid1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        sportid1txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sportid1txtKeyPressed(evt);
            }
        });

        info.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        info.setText("(Enter Sport Id of the Sport to be removed)");

        removesportsubmit1.setBackground(new java.awt.Color(255, 255, 102));
        removesportsubmit1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        removesportsubmit1.setText("SUBMIT");
        removesportsubmit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removesportsubmit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removesportsubmit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removesportsubmit1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        removesportsubmit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removesportsubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removesportsubmit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removesportholderLayout = new javax.swing.GroupLayout(removesportholder);
        removesportholder.setLayout(removesportholderLayout);
        removesportholderLayout.setHorizontalGroup(
            removesportholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removesportholderLayout.createSequentialGroup()
                .addGroup(removesportholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(removesportholderLayout.createSequentialGroup()
                        .addGroup(removesportholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sportid1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sportid1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(removesportholderLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(removesportsubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        removesportholderLayout.setVerticalGroup(
            removesportholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removesportholderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sportid1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sportid1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removesportsubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        holder.add(removesportholder);
        removesportholder.setBounds(600, 540, 270, 130);

        sportsholder.setBackground(new java.awt.Color(255, 255, 255));
        sportsholder.setBorder(null);
        sportsholder.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sportsholder.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        sportsholder.setOpaque(false);

        sportstable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sportstable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sportstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SPORTS ID", "NAME", "FEE", "TIMINGS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sportstable.setEnabled(false);
        sportstable.setGridColor(new java.awt.Color(0, 0, 0));
        sportstable.setOpaque(false);
        sportstable.setRowHeight(25);
        sportstable.setRowMargin(2);
        sportstable.setRowSelectionAllowed(false);
        sportstable.setShowGrid(true);
        sportstable.getTableHeader().setResizingAllowed(false);
        sportstable.getTableHeader().setReorderingAllowed(false);
        sportsholder.setViewportView(sportstable);

        holder.add(sportsholder);
        sportsholder.setBounds(30, 210, 1460, 230);

        sportsheader.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        sportsheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sportsheader.setText("SPORTS");
        sportsheader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        holder.add(sportsheader);
        sportsheader.setBounds(0, 130, 1538, 80);

        imagepic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagepic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harshil\\Pictures\\Saved Pictures\\pic.png")); // NOI18N
        imagepic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        holder.add(imagepic);
        imagepic.setBounds(-20, -20, 1580, 1340);

        javax.swing.GroupLayout supportLayout = new javax.swing.GroupLayout(support);
        support.setLayout(supportLayout);
        supportLayout.setHorizontalGroup(
            supportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, 1538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        supportLayout.setVerticalGroup(
            supportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        carrier.setViewportView(support);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(carrier, javax.swing.GroupLayout.DEFAULT_SIZE, 1538, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(carrier, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1552, 843));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insert()
    {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@Dell-HsB:1521:xe", "HSB", "4803");
            Statement stmt=con.createStatement();
            String query="insert into HSB.sport values ('"+sportidtxt.getText()+"','"+nametxt.getText()+"','"+feetxt.getText()+"','"+timingstxt.getText()+"')";
            ResultSet rs=stmt.executeQuery(query);
            con.close();
            sportidtxt.setText(null);
            nametxt.setText(null);
            feetxt.setText(null);
            timingstxt.setText(null);
            sportidtxt.requestFocus();
           } catch (Exception e) {
            JOptionPane.showMessageDialog(removesport, "SPORT ID ALREADY EXISTS", "ERROR", JOptionPane.ERROR_MESSAGE);
       } 
    }
    
    private void display()
    {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@Dell-HsB:1521:xe", "HSB", "4803");
            Statement stmt=con.createStatement();
            String query="select * from HSB.sport order by sport_id";
            ResultSet rs=stmt.executeQuery(query);
            sportstable.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
           } catch (Exception e) {
            System.out.println(e);
       } 
    }
    
    private void remove()
    {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@Dell-HsB:1521:xe", "system", "0000");
            Statement stmt=con.createStatement();
            String query="delete HSB.sport where sport_id = '"+sportid1txt.getText()+"' ";
            ResultSet rs=stmt.executeQuery(query);
            con.close();
           } catch (Exception e) {
            System.out.println(e);
       } 
    }
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new Home().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JOptionPane.showMessageDialog(sportstable, "SUCCESSFULLY LOGGED OUT", "LOGOUT",JOptionPane.INFORMATION_MESSAGE);
        new SCMS().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void removesportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removesportActionPerformed
        addsportholder.setVisible(false);
        removesportholder.setVisible(true);
    }//GEN-LAST:event_removesportActionPerformed

    private void addsportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsportActionPerformed
        removesportholder.setVisible(false);
        addsportholder.setVisible(true);
    }//GEN-LAST:event_addsportActionPerformed

    private void addsportsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsportsubmitActionPerformed
        if(sportidtxt.getText().isBlank()||nametxt.getText().isBlank()||feetxt.getText().isBlank()||timingstxt.getText().isBlank())
        {
             JOptionPane.showMessageDialog(removesport, "ALL FIELDS ARE MANADATORY", "ERROR", JOptionPane.ERROR_MESSAGE);
        } 
        else
        {
        insert();
        display();
        }
    }//GEN-LAST:event_addsportsubmitActionPerformed

    private void removesportsubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removesportsubmit1ActionPerformed
        if(sportid1txt.getText().isBlank())
        {
            JOptionPane.showMessageDialog(removesport, "ENTER VALID SPORT ID", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            remove();
            display();
            sportid1txt.setText(null);
        }
    }//GEN-LAST:event_removesportsubmit1ActionPerformed

    private void sportidtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sportidtxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
            nametxt.requestFocus();
        }
    }//GEN-LAST:event_sportidtxtKeyPressed

    private void nametxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
            feetxt.requestFocus();
        }
        else
        {
            if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            sportidtxt.requestFocus();
        }
        }
    }//GEN-LAST:event_nametxtKeyPressed

    private void feetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feetxtKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
            timingstxt.requestFocus();
        }
        else
        {
            if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            nametxt.requestFocus();
        }
        }
    }//GEN-LAST:event_feetxtKeyPressed

    private void timingstxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_timingstxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           if(sportidtxt.getText().isBlank()||nametxt.getText().isBlank()||feetxt.getText().isBlank()||timingstxt.getText().isBlank())
        {
             JOptionPane.showMessageDialog(removesport, "ALL FIELDS ARE MANADATORY", "ERROR", JOptionPane.ERROR_MESSAGE);
        } 
        else
        {
        insert();
        display();
        }
        }
        else
        {
            if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            feetxt.requestFocus();
        }
        }
    }//GEN-LAST:event_timingstxtKeyPressed

    private void sportid1txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sportid1txtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            remove();
            display();
            sportid1txt.setText(null);
        }   
    }//GEN-LAST:event_sportid1txtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new Sports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsport;
    private javax.swing.JPanel addsportholder;
    private javax.swing.JButton addsportsubmit;
    private javax.swing.JScrollPane carrier;
    private javax.swing.JLabel fee;
    private javax.swing.JTextField feetxt;
    private javax.swing.JLabel header;
    private javax.swing.JPanel holder;
    private javax.swing.JButton home;
    private javax.swing.JLabel imagepic;
    private javax.swing.JLabel info;
    private javax.swing.JButton logout;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton removesport;
    private javax.swing.JPanel removesportholder;
    private javax.swing.JButton removesportsubmit1;
    private javax.swing.JLabel sportid;
    private javax.swing.JLabel sportid1;
    private javax.swing.JTextField sportid1txt;
    private javax.swing.JTextField sportidtxt;
    private javax.swing.JLabel sportsheader;
    private javax.swing.JScrollPane sportsholder;
    private javax.swing.JTable sportstable;
    private javax.swing.JPanel support;
    private javax.swing.JLabel timings;
    private javax.swing.JTextField timingstxt;
    // End of variables declaration//GEN-END:variables
}
